# Generated by Django 4.2.1 on 2023-07-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='l_name',
        ),
    ]
